"""Create veiculos table (try 3)

Revision ID: 01dac0b94325
Revises: 
Create Date: 2025-03-29 11:55:32.431376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dac0b94325'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=True),
    sa.Column('ano_modelo', sa.Integer(), nullable=True),
    sa.Column('combustivel', sa.String(length=50), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('quilometragem', sa.Integer(), nullable=True),
    sa.Column('numero_portas', sa.Integer(), nullable=True),
    sa.Column('transmissao', sa.String(length=50), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_ano_modelo'), 'veiculos', ['ano_modelo'], unique=False)
    op.create_index(op.f('ix_veiculos_id'), 'veiculos', ['id'], unique=False)
    op.create_index(op.f('ix_veiculos_marca'), 'veiculos', ['marca'], unique=False)
    op.create_index(op.f('ix_veiculos_modelo'), 'veiculos', ['modelo'], unique=False)
    op.create_index(op.f('ix_veiculos_preco'), 'veiculos', ['preco'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculos_preco'), table_name='veiculos')
    op.drop_index(op.f('ix_veiculos_modelo'), table_name='veiculos')
    op.drop_index(op.f('ix_veiculos_marca'), table_name='veiculos')
    op.drop_index(op.f('ix_veiculos_id'), table_name='veiculos')
    op.drop_index(op.f('ix_veiculos_ano_modelo'), table_name='veiculos')
    op.drop_table('veiculos')
    # ### end Alembic commands ###
